#+Author: Prof. Dr. Christoph Schottmüller
#+Title: Thesis Guidelines

#+LATEX_CLASS_OPTIONS: [a4paper]
#+latex_header: \usepackage[tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm]{geometry}
#+latex_header: \usepackage{setspace}\onehalfspacing

* Finding a topic
The most important part is that you are interested in your topic. After all you will spend quite some with it. You can draw on many sources in order to find a topic:
- the news. Some economic or political problem might pop up that you find interesting. Magazines with somewhat longer articles (like the Economist or the New Yorker) could be especially helpful.
- your student job. Your job might give you a lot of background and inside information on certain questions which gives you a head start when analyzing.
- your hobbies. You are an avid stamp collector and want to write about some interesting features of the market for stamps? Why not?
- books; and I do not necessarily mean textbooks. I had the idea for a paper of mine while reading the description of Bentham's panopticon in a book that had nothing to do with economics. When reading the description I realized that this was a strategic problem that would merit some game theoretic modeling.
- academic papers. Analyzing a variation of a published paper is a good approach for a thesis. Survey articles as published in [[https://www.aeaweb.org/journals/jel][Journal of Economic Literature]], [[https://www.aeaweb.org/journals/jep][Journal of Economic Perspectives]], Elsevier's [[https://www.sciencedirect.com/science/handbooks/sub/economics/all][Handbook of Economics]] series and also the [[http://www.dictionaryofeconomics.com][New Palgrave Dictionary of Economics]] might give you a decent background on a topic you are considering.
- policy and legal documents. An economic analysis of certain proposals (or decisions in competition policy cases) can make an interesting thesis.
- your course work. However, students tend to over-rely on this last channel. 

You also might keep in mind what you want to do after your studies. Your thesis can be an entry ticket into a certain kind of career/sector, e.g. future employers might be more inclined to interview you if they can see that you wrote a thesis on a topic that is relevant to them.

** Most common thesis types (supervised at the chair for microeconomics)
The following list is not exhaustive but if you have something different in mind we should talk about it first.

- You pick a topic, e.g. from the news, you find interesting and analyze it using a game-theoretical model (some computational or empirical parts are, of course, fine as well; however, we can usually not procure the data for empirical analysis).
- You start from a published paper, describe the results and add a small original contribution of your own that you compare with the paper. Your contribution could be
  - changing some assumption or introduce an additional variable (or use a different solution concept),
  - a variation of the model (often it is useful to first simplify the model in some dimension by making some additional assumptions before extending it in another dimension),
  - a numerical solution/simulation that illustrates aspects of the model in the paper which have not been or cannot be shown analytically and possibly extend the results or model of the paper for the specific functional form or parameter values you chose,
  - writing down and solving a game-theoretic model addressing points made only verbally in the assigned paper.
-  You analyze a competition policy decision. This will usually be a decision by DG Comp, the General Court ( formerly known as Court of First Instance) or the European Court of Justice. You check whether the reasoning in the decision makes economic sense by modeling the reasoning using models from IO, game theory and contract theory. (Please, note that the definition of the relevant market takes usually a lot more space in these decisions than it should in your thesis.)
- comparative literature survey. This is usually not the first choice because it is very difficult to do this properly. The idea is that you show why different results are obtained in different papers and how this depends on their assumptions. Hence, you try not to summarize one paper after another but to explain the logic underlying a whole literature.[fn:1] 

** Is my topic (candidate) appropriate for a thesis?

After identifying a potential topic you should ask yourself "Can I make this into a thesis?" Microeconomic modeling is to a large extent simply a way to tell a story about trade-offs. Consequently, you should ask yourself the following questions:
- what is the story?
- who are the players?
  - what is their information?
  - what are their actions?
- *what trade-offs do players face?*
- what strategic effects may result; how do players respond strategically to other players
- is there a simple framework in which I can capture this story/trade-off/strategic effect?
- is there the potential to learn something new?
- what could be a possible result/conclusion of the thesis? (it will eventually be very different, but to formulate a possible result helps you to see what kind of things you might strive for and whether the topic is sufficiently rich for a thesis)
- can you explain to your friends why this is a good thesis topic?

* Writing a proposal

When you have thought through the questions above, you write up a research proposal of one or two pages (summing up your thoughts/answers and particularly addressing the questions mentioned in the section "Is my topic (candidate) appropriate for a thesis?") and send this proposal to the responsible person at my chair (currently Marius Gramb). It should contain your main question, answers to (some of) the questions above (1.2), and some first ideas regarding the methods with which you want to tackle the problem. We will read it and then we meet to discuss the proposal (or refer you to a colleague of mine who is better suitable to supervise your project). We might conclude that the proposal should be changed a bit or we might immediately go ahead and do the paper work, talk about a rough schedule etc.

* Supervision
We do not have a fixed format for supervision as the needs will differ from thesis to thesis. However, there is some minimum structure that applies generally:
- We want to see a proposal (~1-2 pages); preferably before meeting for the first time. (If we meet before you have a proposal, we usually cannot tell you much more than is written in this document.) 

- We have a midterm review to take stock and to see how you are doing on time.

It is very tempting to ask your supervisor all the time what to do next. However, keep in mind that a thesis is an /independent/ piece of work and the novelty of /your ideas/ is part of the evaluation.

* Writing
- Have a clear structure. 
- It is a good idea to state one (or several) research question(s) at the beginning, answer this/these question(s) in the analysis and summarize the answers in the conclusion. (Note that you do not have to know all these questions when you start working on the thesis, some things will pop up while working.)
- Make sure to use some tool(s) that is (are) taught in an elective course you took. This way you avoid writing a thesis that is not at the appropriate level.
- Use a consistent citation style. Economists mainly use the /author (year)/ style.
- Use the /proposition-proof/ style; i.e. state a result formally in a proposition (or lemma or theorem), explain it intuitively in the main text and add a formal proof (possibly in an appendix).
- Include a literature section where you place your thesis in the related literature. Google Scholar is probably the easiest way to find related literature. The most relevant articles tend to be published in very good journals. A very subjective and certainly incomplete list of decent journals (for microeconomics papers) is the following: American Economic Review, Econometrica, Review of Economic Studies, Journal of Political Economy, Quarterly Journal of Economics, Journal of Economic Theory, Theoretical Economics, RAND Journal of Economics, Games and Economic Behavior, Economic Journal, Journal of the European Economic Association, International Economic Review.
  - To be able to download academic papers without having to pay for it yourself, you have to be either on campus or connect to the university via VPN.
  - The [[https://www.vwlbibliothek.uni-koeln.de/][economics library]] offers courses in literature search and scientific working methods. Please contact the library staff if you feel that you need help in these areas.

- In terms of style, structure etc., it may be a good idea to mimick papers published in the journals above.
- You do yourself and your readers a favor if you write in LaTeX (and use BibTeX). The LaTeX [[https://en.wikibooks.org/wiki/LaTeX][wikibook]] will be a great ressource in this case. Some LaTeX template with explanations can be found on my [[https://schottmueller.github.io/#teaching][website]].


* Some general remarks
- Keep in mind that a model is a conscious over-simplification of reality. If you want to analyze a certain problem, it is usually not helpful to try to stack everything you have heard about this problem in one model (and then make it dynamic in continuous time etc.). Such models tend to be intractable and therefore absolutely useless. Focus on some specific aspect/effect and try to get the smallest possible model in which you can see the effect. You can generalize later on if you like (and time permits).
- Your thesis can contain several small models if you want to explain several effects. There is no need to stack everything into one grand model, see above.
- You should reserve a decent amount of time at the end for editing only. For a master thesis I would recommend no less than two weeks. Part of the evaluation of a thesis is whether it is well written.

- You should write in English.

* Useful sources for how to write/model
- Hal Varian's "How to build an economic model in your spare time", [[http://people.ischool.berkeley.edu/~hal/Papers/how.pdf][link]]


[fn:1] Switching to this format can be an option if you cannot manage to get anything sensible out of a model (thesis type: start from a published paper) but you have read the related papers so well that you have a clear idea of the literature. 
