#+TITLE: Information and Strategy
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+cite_export: csl ../static/econometrica.csl
#+bibliography: ../static/references.bib
#+HTML_HEAD: <link rel="icon" href="./icons/teacher.webp">
* News
 - There are new lecture notes for the topic "hard evidence" on sciebo.
 - The paper we discuss on Nov. 14 can be downloaded [[https://schottmueller.github.io/papers/echoChamber/echo_chambers.pdf][here]] (you need a vpn to the campus or be on campus to download). Please, read the paper using the methodology described in the guide on how to read a paper.
 - The paper we discuss on Nov. 7 can be downloaded [[https://doi.org/10.1287/mnsc.2017.2913][here]] (you need a vpn to the campus or be on campus to download). Please, read the paper using the methodology described in the guide on how to read a paper.
 - The paper we discuss on Oct. 17 can be downloaded [[http://dx.doi.org/10.1016/j.jmateco.2015.01.005][here]] (you need a vpn to the campus or be on campus to download). Please, read the paper using the methodology described in the guide on how to read a paper.
# - The first student presentation is already on Dec. 19 where we will also discuss a bit how the presentations could look like. Presentations should take between 30 and 45 minutes (the 45 minutes is including questions and discussion). If you are using slides , please send those to me as *pdf* before your presentation. You have to use your own computer if you use power point or other formats for your slides.   
 # - For Thursday Dec 10, we are discussing a paper that is not published yet. Please, use the version [[https://schottmueller.github.io/papers/echoChamber/echo_chambers.pdf][here]].
# - This website will be slowly updated over the coming weeks to give students information about the course "Information and Strategy".
# - On November 18 we will have a practice session on cheap talk. Please, read this [[https://schottmueller.github.io/papers/echoChamber/echo_chambers.pdf][paper]] in advance following the steps in the [[https://github.com/schottmueller/infoStrat/files/3615401/htrap.pdf][guide]].
# - As a lot more students than expected signed up for the course, presentations may be group presentations.   
# - Due to an illness the first week's lecture will not go along as planned on campus. Instead we will have an online lecture on zoom on Oct 12, 9am. The lecture will be recorded. You can download the recording [[https://uni-koeln.sciebo.de/s/0txSevFVvl3Q7Tl][here]].
- Lecture time and place in WS 2024/25: Thursday (100 HS XVIIa) 9:00-11:30.

* Description
This course deals with information economics. That is, how do people and/or organizations, that have access to different information sources, strategically interact? We also deal with the natural follow up question: Who will and/or should have access to what information and what kind of information can/will/should be transmitted from one person to another? 

There are numerous applications from all fields of economics. These cover classic questions, like: how will a firm design its pricing schedule, e.g. what kind of quantity discounts to use, if it does not know the willingness to pay of its customers? But also modern questions, e.g. "how does the internet change the way in which people communicate and obtain information, say, about politics?" or "to what extent should, so called, stress tests by the banking supervisors reveal information about default risks of banks?".   

The course uses mainly game theoretic models in order to shed light on questions similar to those above. Methodologically, students get to know the basic models of information economics (screening, cheap talk, information design etc.). This will enable students to read research papers in which these tools are used. 

** Objective
The course has various goals. First, students get to know the blockbuster ideas in information economics and learn how to use these in order to gain insights into various economic problems. Second, students learn how to read research papers. The latter skill tends to be useful when working on seminar papers or a thesis. The former tends to be useful in life.

** Grading

Grading is based on a presentation and a written report. Both the presentation and the report are on a research paper in information economics. The main task is to summarizes the paper and (mainly in the written report) to briefly evaluate the paper, discuss it or comment on it. The page limit for the report is 6 pages. Note that this course is not a so-called "Seminar". The main difference to a seminar is that (i) the majority of the course consists of lectures, (ii) you do not have to produce an own original contribution in the report and consequently the report is shorter than a typical seminar paper. 

If a student prefers to write a research proposal instead of a report, this is possible as well.

Presentations have to be in English. Reports can be written in English or German.

Attendance is voluntary and does not affect the grading of your report directly. (Of course, the lectures are intended to prepare you for writing a good report...)  Attending the student presentations is strongly encouraged.

*** Important dates
- Insert your paper preferences [[https://docs.google.com/spreadsheets/d/1HqaHmdN_IwvYXpi1jSxLkJl1THz5kUEX8bBCaveDRqg/edit?usp=sharing][here]] before October 27, 1:00pm. A list of papers ordered by topic as well as a bibliography can be found at the bottom of this page. Papers are assigned in the following week. There is no guarantee that you are assigned one of your preferred papers.
# - Send an email to the course instructor with your preferred papers (up to 5) by November 11, 8:00am. Papers are assigned in the following week. There is no guarantee that you are assigned one of your preferred papers.
  # Please, also indicate whether you prefer to present on campus or online via zoom.
- Register for the "examination" via KLIPS by November 4. Deregistration will not be possible after November 4 for scheduling reasons.
- Dates for the presentations are announced in November. Student presentations take place in January and February (also end of December if many students sign up).
- Hand in your paper by February 28 via email. 
** Presentation

- The goal of the presentation is to teach your fellow students. This implies that you should make the presentation such that it is (i) understandable by your fellow students and (ii) focuses on the interesting bits of the paper. To "teach" does not only mean to state the main results but ideally you should give an intuition/idea why these results hold (at least under the assumptions made in the paper) and also an idea what this means for applications.

- You do not have to present all results and extensions of the paper, i.e. you can focus on the main result.

- You can simplify the model if this makes the presentation easier without losing the main results (e.g. only present the model for 2 instead of n players or with a uniform distribution instead of a general distribution F etc.).

- You can also search for motivations/applications that are not mentioned in the paper and talk about those if this serves your purpose.

- Assuming that your fellow students attended the lectures, it can be a good idea to compare the model of your paper to the closest model discussed in the lecture (and explain what is different). Seeing the connections can often  help to understand the mechanisms at work better.

- It is difficult to follow a lot of (long) equations. Hence, you should have only equations that help to understand what is going on. If you have an equation on your slides, you should probably explain it term by term (otherwise the audience will not have the time to take it in).

- I do not expect you to replicate all the proofs. This quickly gets boring and hard to follow. In a presentation, it is more important to give an intuition why a result holds than to prove it. (The same is true for your report!)

- At the end you may also discuss directions for further research, highlight weaknesses of the paper or comment on the applicability. This part is not essential for the presentation but you should definitely have it in your report. So, why not try already in the presentation and see whether you get some feedback?

- If you use slides, please send them to me the evening before your presentation (6pm) *in pdf format*. 

- The time frame will probably be around 30 minutes. However, this can depend on the number of students in the course. (In the unlikely event that surprisingly many students take the course, presentations may be in teams. )


* Course material
# ** Slides of student presentations
# - You can find the slides [[https://web.tresorit.com/l/Wekrb#qBdyy0DRm5p_rbrwP1CEYg][here]].

** Lecture material
- adverse selection slides: [[https://github.com/schottmueller/microMSc/blob/main/slides/lemons.org][org]] [[https://web.tresorit.com/l/uHpHt#H4BNhZHSj9-AkWIwpG4BnQ][pdf]]   
- [[./files/htrap.pdf][guide]] on how to read a paper
- [[https://github.com/schottmueller/infoStrat/files/7323109/envelopeMonoNonLinPric.pdf][handout]] on screening with a continuum of types
- reading material is shared via [[https://uni-koeln.sciebo.de/s/xECzExjwU9sC2Db][sciebo]] (password announced in lecture)
# pw: infoStrat  
  
** Books
Some of the lectures are based on parts of books. Noteworthy are
- [cite:@bolton2005contract] 
- [cite:@campbell2018incentives]

* Plan

The *structure of the course* is as follows: In the first part of the course, there will mainly be lectures on information economics and its applications. However, we will have a few "practice sessions" in which we discuss a paper that all students should have read/skimmed before. These sessions add to the material of the lecture but are also meant to give you some practice in "how to read a paper (quickly)," i.e. these sessions prepare students for their presentations and reports. The second (and shorter) part of the course consists of student presentations of papers in information economics.

** Introduction to asymmetric information

We use the first 2-3 weeks to introduce the classics in information economics. We see that asymmetric information can lead to inefficiencies in markets and start to discuss what measures players/markets may use to avoid these inefficiencies (at least partially). However, we also see that the clever use of information asymmetries can make everyone better off in some cases. 

*** Adverse selection: Akerlof's lemons market
- Akerlof's lemons market
- the first welfare theorem does not hold if different players have different information 
- applications: used car markets and warranties, adverse selection in insurance markets
- sources: chapter 5.3 in [cite:@campbell2018incentives]
# - practice: excessive self financing or insurance as in cite:einav2011selection

*** Mediation and correlated equilibrium
- correlated equilibrium
- an impartial mediator can use asymmetric information to make everyone better off
- sources for the technical details: chapter 8 in [cite:@maschler2013game]
- practice: [cite:@jann2015correlated ]

*** Information rents and screening
- 2 type screening problem and revelation principle
- information creates "rents" for those who have information but uninformed parties reduce these rents by distorting allocations inefficiently
- applications: non-linear pricing by a monopolist
- technical extension: screening with a continuum of types (handout)
- sources: chapter 2.1.3 and 2.3.3 in  [cite:@bolton2005contract]
# - practice: cite:boone2009optimal 
# regulating a monopolist, cite:Bar82

** Information design/Bayesian persuasion
Sometimes we can determine how informed others (or we ourselves) will be, e.g. a central bank can decide how to test banks in a "stress test" (and the information the market gets from the test depends on how strict the test is), a prosecutor decides which witnesses to hear in court and a school might decide how finely grained its grade system is. Which design should the information designer optimally choose?
*** Bayesian persuasion
- Bayesian persuasion and the concavification approach
- how can you structure other players' information to reach your goals?
- application: will bad banks fail optimal stress tests?
- sources: [cite:@kamenica11_bayes_persuas]
- practice: [cite:@schweizer2018optimal]
*** Bayes correlated equilibrium
- the BCE approach to information design
- sources: section 1-3.2 in [cite:@bergemann19_infor_desig]
# - practice: tba

** Strategic communication (cheap talk)
People might share what they know with others. The recipients of the information might be able to make use of this information when choosing what to do; e.g. you might go to a new restaurant if someone tells you it is great. This, however, opens the door for manipulation: For example, the restaurant owner might pay people to give positive reviews to others. Which sender and which messages can be trusted to what extent?
*** Homophily and echo chambers
- discrete state cheap talk
- People mainly communicate with people that are similar to them. Is this inefficient or could there be an informational reason?
- application: communication and the internet, echo chambers
- practice: [cite:@jann2018echo]
# - practice: cite:farrell1989cheap
*** Continuous state
- classic cheap talk model with a continuum of states
- applications: delegation
- sources: [cite:@crawford1982cheap]
- practice: [cite:@schottmueller2013cifd]

** Hard evidence
Sometimes one can communicate information credibly by having a third party expert certifying it; e.g. rating agencies can certify the quality of an asset or the creditworthiness of a person, one can take a test - like GRE or TOEFL - to certify certain abilities etc. Who will certify what? Which information will be transmitted and which won't?
*** complete unraveling
- the incentive to show that one is better than the rest can lead to complete information unraveling 
- applications: privacy legislation
- sources: ch. 5.1 in [cite:@bolton2005contract], (background: [cite:@milgrom1981good])
*** partial unraveling
- costly certification and noisy certification (Dye's model)
- who will certify if the unravelling logic does not apply completely?
- applications: should students be able to choose among exam questions?, risk taking (BDL) 
- sources: [[https://sites.google.com/site/eddiedekelsite/pres_address_2016_slides/pres_address_2016_slides.pdf?attredirects=0&d=1][Dekel's slides]], (background: [cite:@dye1985disclosure],[cite:@jung1988disclosure])
# - practice: cite:ben2014optimal
# ** certification
# cite:strausz2005honest,stahl2017certification 

** Reputation and advice

Interacting repeatedly allows to build a reputation. E.g. if a friend has never lied to you, you may expect him not to lie in the future. The friend has a reputation for honesty. Can a strategic friend (who might occasionally have an incentive to lie to you) be always honest? If there are benefits from being perceived as honest, how will a friend behave today?

*** Chain store paradox and reputation
- Can players commit to a certain action that they would normally not take when interacting several times?
- applications: reputation for behavior
- sources: ch. 9.1-9.2, 9.4 in [cite:@fudenberg1991game]
# - practice: http://didattica.unibocconi.it/mypage/dwload.php?nomefile=48805_20081010_094047_CENTRAL_BANK_REPUTATION_AND_THE_MONETIZATION_OF_DEFICITS20140415110809.PDF or Barro, Gordon JME 1983

***  Career concerns
- How will concerns about the future affect a person's decision about how much effort to exert today?
- sources: [cite:@holmstrom1999managerial]

*** advice
- Will experts give best possible advice if they are motivated by an incentive to show the world that they are great experts?
- sources: [cite:@ottaviani2006professional]


* List of papers for presentation

These are some papers that students may choose to present. If you want to present a paper that is not on the list, please contact the course instructor.

# ** Correlated equilibrium
# - cite:liu1996correlated
** Adverse selection and screening
# - cite:martimort2009market
- [cite:@che1993design]
- [cite:@ber07]
- [cite:@corrao23nonlinear]
- [cite:@bobkova2024information]
- [cite:@martimort2009market]
- [cite:@bijlsma2012competition]
- [cite:@curello2020screening]
  
** Information design
# - cite:condorelli2020information
- [cite:@taneva2018information]
- [cite:@bergemann16_bayes_correl_equil_compar_infor_struc_games]
- [cite:@bergemann2015limits]
- [cite:@bergemann2015selling]
- [cite:@bergemann17_first_price_auction_with_gener_infor_struc]
- [cite:@baliga2016torture]
- [cite:@ely2017beeps]
- [cite:@mylovanov2017optimal]
- [cite:@goldstein2018stress]
- [cite:@bergemann18_desig_price_infor]
- [cite:@lipnowski24perfect]
- [cite:@shishkin2019evidence]
- [cite:@mathevet2020information]
- [cite:@alonso2016persuading]
  
** Hard evidence
- [cite:@demarzo2018test]
- [cite:@song2003disclosures]
- [cite:@pram20disclosure]
- [cite:@nageeb2019voluntary]
- [cite:@shishkin2019evidence]
- [cite:@asseyer2024certification]

** Strategic communication (cheap talk)
# - cite:farrell1989cheap
# - cite:dessein2002authority
- [cite:@stein1989cheap]
- [cite:@alonso2008does]
- [cite:@battaglini2002multiple]
- [cite:@galeotti2013strategic]
- [cite:@deimen2019delegated]
- [cite:@deimen2020authority]
- [cite:@penn2016engagement]
- [cite:@dewan2016defense]
- [cite:@patty2024designing]

** Reputation and advice
- [cite:@sobel1985theory]
- [cite:@prendergast1993theory]
- [cite:@prendergast1996impetuous]
- [cite:@ely03]
- [cite:@par05]
- [cite:@prat2005wrong]
- [cite:@ottaviani2006reputational]
- [cite:@bhaskar2019culture]
- [cite:@jullien2014new]
- [cite:@aghion2014inducing]
- [cite:@klein2017will ]
- [cite:@neeman2019benefit]
- [cite:@levine2021reputationTrap]


* Bibliography

#+print_bibliography:

