#+TITLE: Information and Strategy
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

* News
- The lecture on Nov 16 is canceled due to health reasons.
- The paper we discuss on Nov. 23 can be downloaded [[https://schottmueller.github.io/papers/echoChamber/echo_chambers.pdf][here]] (you need a vpn to the campus or be on campus to download). Please, read the paper using the methodology described in the guide on how to read a paper.
- The paper we discuss on Nov. 9 can be downloaded [[https://doi.org/10.1287/mnsc.2017.2913][here]] (you need a vpn to the campus or be on campus to download). Please, read the paper using the methodology described in the guide on how to read a paper.
# - The paper we discuss on Oct. 19 can be downloaded [[http://dx.doi.org/10.1016/j.jmateco.2015.01.005][here]] (you need a vpn to the campus or be on campus to download). Please, read the paper using the methodology described in the guide on how to read a paper.
# - The first student presentation is already on Dec. 19 where we will also discuss a bit how the presentations could look like. Presentations should take between 30 and 45 minutes (the 45 minutes is including questions and discussion). If you are using slides , please send those to me as *pdf* before your presentation. You have to use your own computer if you use power point or other formats for your slides.   
 # - For Thursday Dec 10, we are discussing a paper that is not published yet. Please, use the version [[https://schottmueller.github.io/papers/echoChamber/echo_chambers.pdf][here]].
# - This website will be slowly updated over the coming weeks to give students information about the course "Information and Strategy".
# - On November 18 we will have a practice session on cheap talk. Please, read this [[https://schottmueller.github.io/papers/echoChamber/echo_chambers.pdf][paper]] in advance following the steps in the [[https://github.com/schottmueller/infoStrat/files/3615401/htrap.pdf][guide]].
# - As a lot more students than expected signed up for the course, presentations may be group presentations.   
- Due to an illness the first week's lecture will not go along as planned on campus. Instead we will have an online lecture on zoom on Oct 12, 9am. The lecture will be recorded. You can download the recording [[https://uni-koeln.sciebo.de/s/0txSevFVvl3Q7Tl][here]].
- Lecture time and place in WS 2023/24: Thursday (100 HS XIa) 9:00-11:30.

* Description
This course deals with information economics. That is, how do people and/or organizations, that have access to different information sources, strategically interact? We also deal with the natural follow up question: Who will and/or should have access to what information and what kind of information can/will/should be transmitted from one person to another? 

There are numerous applications from all fields of economics. These cover classic questions, like: how will a firm design its pricing schedule, e.g. what kind of quantity discounts to use, if it does not know the willingness to pay of its customers? But also modern questions, e.g. "how does the internet change the way in which people communicate and obtain information, say, about politics?" or "to what extent should, so called, stress tests by the banking supervisors reveal information about default risks of banks?".   

The course uses mainly game theoretic models in order to shed light on questions similar to those above. Methodologically, students get to know the basic models of information economics (screening, cheap talk, information design etc.). This will enable students to read research papers in which these tools are used. 

** Objective
The course has various goals. First, students get to know the blockbuster ideas in information economics and learn how to use these in order to gain insights into various economic problems. Second, students learn how to read research papers. The latter skill tends to be useful when working on seminar papers or a thesis. The former tends to be useful in life.

** Grading

Grading is based on a presentation and a written report. Both the presentation and the report are on a research paper in information economics. The main task is to summarizes the paper and (mainly in the written report) to briefly evaluate the paper, discuss it or comment on it. The page limit for the report is 6 pages. Note that this course is not a so-called "Seminar". The main difference to a seminar is that (i) the majority of the course consists of lectures, (ii) you do not have to produce an own original contribution in the report and consequently the report is shorter than a typical seminar paper. 

If a student prefers to write a research proposal instead of a report, this is possible as well.

Presentations have to be in English. Reports can be written in English or German.

Attendance is voluntary and does not affect the grading of your report directly. (Of course, the lectures are intended to prepare you for writing a good report...)  Attending the student presentations is strongly encouraged.

*** Important dates
- Insert your paper preferences [[https://docs.google.com/spreadsheets/d/1HqaHmdN_IwvYXpi1jSxLkJl1THz5kUEX8bBCaveDRqg/edit?usp=sharing][here]] before November 2, 1:00pm. Papers are assigned in the following week. There is no guarantee that you are assigned one of your preferred papers.
# - Send an email to the course instructor with your preferred papers (up to 5) by November 11, 8:00am. Papers are assigned in the following week. There is no guarantee that you are assigned one of your preferred papers.
  # Please, also indicate whether you prefer to present on campus or online via zoom.
- Register for the "examination" via KLIPS by November 9. Deregistration will not be possible after November 12 for scheduling reasons.
- Dates for the presentations are announced in November. Student presentations take place in January and February (also end of December if many students sign up).
- Hand in your paper by February 28 via email. 
** Plan

A preliminary plan can be found [[https://github.com/schottmueller/infoStrat/blob/master/plan21.org][here]]. (A less often updated pdf with properly formatted references is available [[https://github.com/schottmueller/infoStrat/files/7154183/plan21.pdf][here]].)

The *structure of the course* is as follows: In the first part of the course, there will mainly be lectures on information economics and its applications. However, we will have a few "practice sessions" in which we discuss a paper that all students should have read/skimmed before. These sessions add to the material of the lecture but are also meant to give you some practice in "how to read a paper (quickly)," i.e. these sessions prepare students for their presentations and reports. The second (and shorter) part of the course consists of student presentations of papers in information economics.

** Presentation

- The goal of the presentation is to teach your fellow students. This implies that you should make the presentation such that it is (i) understandable by your fellow students and (ii) focuses on the interesting bits of the paper. To "teach" does not only mean to state the main results but ideally you should give an intuition/idea why these results hold (at least under the assumptions made in the paper) and also an idea what this means for applications.

- You do not have to present all results and extensions of the paper, i.e. you can focus on the main result.

- You can simplify the model if this makes the presentation easier without losing the main results (e.g. only present the model for 2 instead of n players or with a uniform distribution instead of a general distribution F etc.).

- You can also search for motivations/applications that are not mentioned in the paper and talk about those if this serves your purpose.

- Assuming that your fellow students attended the lectures, it can be a good idea to compare the model of your paper to the closest model discussed in the lecture (and explain what is different). Seeing the connections can often  help to understand the mechanisms at work better.

- It is difficult to follow a lot of (long) equations. Hence, you should have only equations that help to understand what is going on. If you have an equation on your slides, you should probably explain it term by term (otherwise the audience will not have the time to take it in).

- I do not expect you to replicate all the proofs. This quickly gets boring and hard to follow. In a presentation, it is more important to give an intuition why a result holds than to prove it. (The same is true for your report!)

- At the end you may also discuss directions for further research, highlight weaknesses of the paper or comment on the applicability. This part is not essential for the presentation but you should definitely have it in your report. So, why not try already in the presentation and see whether you get some feedback?

- If you use slides, please send them to me beforehand *in pdf format*. 

- The time frame will probably be around 30 minutes. However, this can depend on the number of students in the course. (In the unlikely event that surprisingly many students take the course, presentations may be in teams. )


* Course material
# ** Slides of student presentations
# - You can find the slides [[https://web.tresorit.com/l/Wekrb#qBdyy0DRm5p_rbrwP1CEYg][here]].

** Lecture material
- adverse selection slides: [[https://github.com/schottmueller/microMSc/blob/main/slides/lemons.org][org]] [[https://web.tresorit.com/l/uHpHt#H4BNhZHSj9-AkWIwpG4BnQ][pdf]]   
- [[https://github.com/schottmueller/infoStrat/files/3615401/htrap.pdf][guide]] on how to read a paper
- [[https://github.com/schottmueller/infoStrat/files/7323109/envelopeMonoNonLinPric.pdf][handout]] on screening with a continuum of types

** Books
Some of the lectures are based on parts of books. Noteworthy are
- Bolton P. and Dewatripont M., "Contract theory", MIT Press 2005,
- Campbell D.E., "Incentives: motivation and the economics of information", Cambridge University Press 2018.

For more specific reading material and references to research papers, check the course [[https://github.com/schottmueller/infoStrat/files/7154183/plan21.pdf][plan]].
