#+OPTIONS:    H:2 num:nil toc:nil \n:nil  TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc 
#+TITLE:
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+AUTHOR:    Christoph Schottmueller
#+DATE:  
#+LANGUAGE:   en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" />
#+HTML_HEAD_EXTRA: <link rel="alternate stylesheet" type="text/css" href="stylesheets/github-dark.css" />


#+BEGIN_HTML    
<header>     
<div class="container">    
<h1>Gametheory 2015</h1>        
<h2>Material for the Game Theory course at the University of Copenhagen</h2>      </div>   
</header>
 <div class="container">
      <section id="main_content">
#+END_HTML

* Organization

The official course description (including schedule, exam requirements etc.) can be found [[http://kurser.ku.dk/course/a%c3%98ka08076u][here]]. The 2014 lecture schedule is [[https://schottmueller.github.io//gt/lectureschedule.html][here]].

Lectures: Wednesday 12.00-15.00 in CSS 2-1-12 

If you have not taken Micro C (or forgotten most of it...), you might want to (re-)read chapters 1.1-1.3, 2.1-2.2, 2.4 and 3.1 in Robert Gibbons' Game Theory book before the course starts.

** Midterm
The midterm is a take home exam. You have to pass the midterm in order to be admitted to the final exam. The midterm can be done in groups up to three people (recommended!)

** Final Exam
The final is an oral exam (with 20 minutes closed book preparation time). You can find the exact exam schedule on Absalon.

* Material
** Lectures
- L01: [[./L01_expectedU/lecture01_expected_utility.pdf][slides]], [[./L01_expectedU/lottery_comp.html][extra]]
- L02: tba

** Handouts
- Handout on [[https://schottmueller.github.io/gt/limits.pdf][limits]]
- Handout on [[https://schottmueller.github.io/gt/refinements.pdf][refinements]] (kindly provided by Hans Keiding)


#+HTML: </div></section>
