#+OPTIONS:    H:2 num:nil toc:nil \n:nil  TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc 
#+TITLE:
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+AUTHOR:    Christoph Schottmueller
#+DATE:  
#+LANGUAGE:   en
#+OPTIONS: html-postamble:"<p>author:\nChristoph\nSchottmueller<br>license:\nCreative\nCommons\nAttribution\nShareAlike\n4\n(author\ncreated\ncontent\nonly)<br>style:\ngithub-dark\n(Apache\nLicense\n2)</p>"
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" />
#+HTML_HEAD_EXTRA: <link rel="alternate stylesheet" type="text/css" href="stylesheets/github-dark.css" />



#+BEGIN_HTML    
<header>     
<div class="container">    
<h1>Gametheory 2016</h1>        
<h2>Material for the GT course at the University of Copenhagen</h2>      </div>   
</header>
 <div class="container">
      <section id="main_content">
#+END_HTML

* Organization

The preliminary lecture schedule is [[https://schottmueller.github.io/gt/lectureplan2016.html][here]].

Lectures: Wednesday 12.00-15.00 in CSS 25-01-53 

If you have not taken Micro C (or forgotten most of it...), you should (re-)read chapters 1.1-1.3.A, 2.1 and 3.1, 3.2 in Robert Gibbons' Game Theory book before the course starts.

** Midterm
The midterm is a take home exam. You have to pass the midterm in order to be admitted to the final exam. The midterm should be done in groups of up to three people.  You have the weeks 42 and 43 (last two weeks of October) to work on the midterm. The midterm exercises will be posted here.
# [[./midterm.pdf][Midterm]]

# Here is a [[./passed_midterm_15_web.xls][list]] with students that are admitted to the final exam. Please, check whether you are on it and contact me if you are not (though you think you should).

** Final Exam
The final is an oral exam (with 20 minutes closed book preparation time). 


* Material
** Handouts
- [[./math_gt.pdf][Math]] for Game Theory
- [[./gt_notation.pdf][Notation]] and preliminaries

** Lectures
- L01: [[./L01_expectedU/lecture01_expected_utility.pdf][slides]], [[./L01_expectedU/lottery_comp.html][extra]]
# - L02: [[./L02_gamesNE/strategic_form_games.pdf ][slides]], [[./L02_gamesNE/Nash_eq_solver2.html][extra]]
- L02: [[./L03_NashThm/Nash_thm.pdf ][slides]], [[./L03_NashThm/Nash_Brouwer.html][extra]]
- L03: [[./L04_rationalizability/ratio.pdf][slides]], [[./L04_rationalizability/rationalizability.html][extra]]
- L04: [[./L05_correlated_eq/corr_eq.pdf][slides]], [[./L05_correlated_eq/correlated_eq_solver_.html][extra]]
- L05:  [[./L07_refinements/perfect.pdf][slides]], [[./L07_refinements/perfect.html][extra]] 
- L06: [[./L07_refinements/extensive_refinements.pdf][slides]]
- L07: [[./L06_supermodular/supermodular.pdf][slides]], [[./L06_supermodular/iasus.html][extra]]
# - L08: discussing the midterm, handout [[./solution_midterm_ex2.pdf][ex 2]]
# - L10/11: [[./L10_11_knowledge/knowledge.pdf][slides]], [[./L10_11_knowledge/knowledge.html][extra]]
# - L12: [[./L12_global/global_games.pdf][slides]], [[./L12_global/global_iter.html][extra]]


** Comment on extra material



The extra material contains some Python code. If you want to find out what this code means, check this simple tutorial on the quantitative economics [[http://quant-econ.net/py/python_by_example.html][website]]. If you want to run the code on your machine (this allows you to try other games than the ones I use as examples), you need to have Python (with the openopt package) installed. You can check the quantitative economics [[http://quant-econ.net/py/getting_started.html][website]] for a guide how to setup and use Python. Note that Python is by default installed on Linux systems (also on Mac?). I use Python 2.7 and the programs might not run in Python 3. To install the openopt package, try (after installing Python – that is after installing Anaconda if you follow the guide) the following in your terminal (or "cmd" if you are running Windows):

#+BEGIN_SRC :exports code
pip install openopt
pip install SpaceFuncs
pip install FuncDesigner
pip install DerApproximator
#+END_SRC

If you are running linux, you might have to add "sudo" in front.




*** some disclaimers
I cannot guarantee that the code in the extra material works flawlessly or produces correct results (though I test it a little bit). Even if it works, the code is very far from being efficient. That is, a proper programmer could write programs that do the job much better and faster. If you are interested in somewhat more professional programs to analyze games, you could check out [[http://www.gambit-project.org/gambit][gambit]]. 

*** FAQs regarding the "extra" material:

- Is the extra material relevant for the exam? Only if it was used directly in the lecture. The code is absolutely irrelevant for the exam.
- Why should I care about the extra material? You do not have to! But…
        - if you want to get some extra practice it might come in handy. You can make up your own exercises and use the programs to check for the correct solutions.
        - some of the material gives you a slightly different angle on things we did in the lecture. This might help you to better understand the topic.
        - playing around with numerical examples helps some people to get a better idea of the problem.
        - being able to go through some basic code is a skill valued in the labor market.
- Is it safe to install the software mentioned above? All the software mentioned here is free and open source software. Python and the openopt suite are widely used in industry and science. Having said that: All code is potentially malicious and I cannot take any responsibility for what happens when you install or use the software.

