#+TITLE:    Game Theory: Supermodular Games\footnote{License: CC Attribution ShareAlike 4.0}
#+AUTHOR:    Christoph Schottmüller
#+EMAIL:     christoph@worknotebook.home
#+DATE:       
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+BEAMER_FRAME_LEVEL: 2
#+latex_header: \mode<beamer>{\useinnertheme{rounded}\usecolortheme{rose}\usecolortheme{dolphin}\setbeamertemplate{navigation symbols}{}\setbeamertemplate{footline}[frame number]{}}
#+latex_header: \mode<beamer>{\usepackage{amsmath}\usepackage{ae,aecompl} \usepackage{sgamevar}}



* Introduction

** Motivation I
- several solution concepts:
   - (dominance)
   - rationalizability (iterative deletion of dominated strategies)
   - Nash equilibrium
   - correlated equilibrium
- Which one to use?
- Are there games where all solution concepts give (approximately) same prediction?

** Motivation II
- comparative statics:
   - how does the equilibrium change if one parameter changes?
      - how do market prices depend on demand elasticity/number of firms in the market/product substitutability?
      - how will the central bank change its interest rate when unemployment rises?
      - how does campaign spending depend on media bias?
   - size of effect has to be estimated but game theoretic models can sometimes determine the sign of effect!
   - are there properties of models under which the sign of the effect is unambiguously clear?

** Example: Search
*** Example: Simple search market 				    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
- $N$ traders exert effort $x_i$ to search for other trader 
- if two traders find each other, each gets benefit 1
- probability that trader $i$ finds other trader is $\min\left\{1,\alpha x_i\left( \sum_{j\neq i}x_j+\beta \right) \right\}$ where $\alpha>0$ and \beta>0 are such that $0<\alpha ((N-1)+\beta)<1$ 
- costs of effort are $x_i^2$ 
*** 							    :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- Given the effort of the others, how much effort should $i$ exert?
- If trader $j$ exerts more effort, how does this affect the optimal effort of $i$?
- If the search technology improves, will a trader exert more or less effort?
- Could our answers depend on the solution concept used?

* Model
** Model Setup: Simple smooth supermodular games
- $N$ players
- action sets $A_i=[\underline y_i,\bar y_i]$
- simultaneous move game
- utility functions: $u_i(a_i,a_{-i})$:
   - $u_i$ is twice continuously differentiable
   - $\frac{\partial^2 u_i}{\partial a_i\partial a_j}\geq 0$ for $i\neq j$ ($\sim$ supermodularity: this is the important assumption of today!)
- check: Does the simple search market satisfy the assumptions?

** What are the effects of $\frac{\partial^2 u_i}{\partial a_i\partial a_j}\geq 0$?
- "Increasing differences":					 
   - let $a_1>a_1'$, then $u_1(a_1,a_2,a_3,\dots)-u_1(a_1',a_2,a_3,\dots)=\int_{a_1'}^{a_1}\frac{\partial u_1}{\partial a_1}(x,a_2,a_3,\dots)\,dx$ is increasing in $a_2$ because of $\frac{\partial^2 u_1}{\partial a_1\partial a_2}\geq 0$
- check: verify that the /simple search market/ satisfies increasing differences
*** Result							    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
Let $a_i>a_i'$. If $u_i(a_i,a_{-i})>u_i(a_i',a_{-i})$, then $u_i(a_i,a_{-i}')>u_i(a_i',a_{-i}')$ for all $a_{-i}'\geq a_{-i}$.     
*** 							    :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- Roughly: Best responses are increasing.

** Serially undominated strategies (another solution concept\dots)
- same as iterative elimination of strictly dominated strategies \\ BUT only pure strategies are used 

1. Which actions of player $i$ are /not/ strictly dominated by pure strategies? Call them $A_i^1$.
2. Which actions of player $i$ are /not/ strictly dominated by pure strategies if the other players play only actions from $A_j^1$? Call them $A_i^2$.
3. Which actions of player $i$ are /not/ strictly dominated by pure strategies if the other players play only actions from $A_j^2$? Call them $A_i^3$.
4. \dots

- note that $A_i^1\supseteq A_i^2\supseteq \dots$
- $U_i=A_i^1\cap A_i^2 \cap\dots$ is the set of *serially undominated strategies* of player $i$

** Example: serially undominated strategies
*** Difference between serially undominated strategies and iterative elimination of strictly dominated actions :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
\begin{table}[h]
\centering
 \begin{game}{3}{3}
       \> L \> C   \>  R\\ 
T   \>6,5  \> 4,2  \> 3,3  \\
M   \>3,0   \> 3,5   \>6,1 \\
B   \>4,1   \>3,0    \>2,16  
\end{game}
\end{table}

** Main result
- let  $\underline u_i$ denote the minimum of $U_i$ and  $\bar u_i$ the maximum of $U_i$
*** Supermodularity Result 1					  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
The strategy profile $(\underline u_1,\underline u_2,\dots)$ is a Nash equilibrium. The strategy profile $(\bar u_1,\bar u_2,\dots)$ is also a Nash equilibrium.
*** 							    :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- Why is this important?
   - $U_i$ gives a range in which
      - all rationalizable actions have to lie in (why?)
      - all Nash equilibria have to be in (why?)
      - the support of all correlated equilibria has to be in (why?)
   - if $\underline u_i$ and $\bar u_i$ are close, all these solution concepts give similar predictions!

** Proof of Supermodularity Result 1
We show that $(\underline u_1,\underline u_2,\dots)$ is NE. 
- Can a deviation to $a_i'<\underline u_i$ or to $a_i'>\bar u_i$ be profitable?
# by definition of $\underline u_i$ all $a_i'<\underline u_i$ are dominated by some other action above $\underline u_i$ (given that all other players use actions in $[\underline u_j,\bar u_j]$; hence, if a deviation $a_i'<\underline u_i$ is profitable, then there is also a deviation $a_i''>\underline u_i$ that is profitable
\vspace*{2cm}

- Can a deviation to $a_i''\in(\underline u_i,\bar u_i]$ be profitable?\\
Suppose it was, i.e. $u_i(a_i'',\underline u_{-i})-u_i(\underline u_i,\underline u_{-i})>0$. Then,\dots
# by increasing differences $u_i(a_i'',a_{-i})-u_i(\underline u_i,a_{-i})>0$ for all $a_{-i}\geq \underline u_i$. But then, $a_i''$ strictly dominates $\underline u_i$ given that the other players use actions in $[\underline u_j,\bar u_j]$. This contradicts $\underline u_i\in U_i$.
\vspace*{2.5cm}

- Similar proof for $(\bar u_1,\bar u_2,\dots)$ (exercise) \hfill\qed

** Extending the result
- Result 1 is only useful if $\bar u_i$ and $\underline u_i$ are close
   - if $\underline u_i=\bar u_i$, then
      - there is a unique  rationalizable action 
      - which is the unique Nash equilibrum
      - which is a unique correlated equilibrium
      - the game can be solved by iterative elimination of strictly dominated strategies
   - note that result implies the following:
***** Corollary							    :B_block:
      :PROPERTIES:
      :BEAMER_env: block
      :END:
If a supermodular game  either
- has a unique pure strategy NE or
- is symmetric and has a unique pure strategy symmetric NE, 

then each player has a unique rationalizable action and the game can be solved by iterative elimination of strictly dominated actions. 
***** 							    :B_ignoreheading:
      :PROPERTIES:
      :BEAMER_env: ignoreheading
      :END:
(why?)

** Is the corollary useful?
- Take /simple search market/ with 2 agents.
   - Determine all pure strategy NE.
   - How many correlated equilibria does this game have?
   - What is the set of rationalizable actions?

- Does the answer change if there are $n$ agents?
** Bertrand with differentiated goods
*** Example: price competition 					  :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
Two firms compete by setting prices. Demand for firm $i$ is
$$D_i(p_1,p_2)=\gamma-p_i+\beta p_j$$
with $0<\beta< 1$ and $\gamma>0$. Costs for firm $i$ are $c_i D_i(p_1,p_2)$. Both firms maximize profits.

*** 							    :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- Is the game supermodular?
- Does it have a unique pure strategy Nash equilibrium?
- What are the sets of rationalizable actions and correlated equilibria?


** Comparative statics I
- Now we want to ask questions like:
   - how does the equilibrium effort in the search market change if $\alpha$ increases?
   - how do the equilibrium prices in the Bertrand game change if $c_i$ changes (or $\beta$) changes?
- now: utility functions depend on actions and a parameter \tau \\
$$u_i(a_i,a_{-i},\tau)$$
hence, lower and upper bounds on serially undominated strategies $\underline u_i$ and $\bar u_i$ are functions of $\tau$
*** Supermodularity Result 2 					  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
If $\frac{\partial^2 u_i}{\partial a_i\partial \tau}\geq 0$ for all $i$, then $\underline{u}_i$ and $\bar u_i$ are increasing in $\tau$.

** Comparative Statics II
- result 2 is especially useful if $\underline u_i(\tau)=\bar u_i(\tau)$
- check:
   - how does the equilibrium effort in the search market depend on $\alpha$?
   - how do the equilibrium prices in the Bertrand game change if $c_i$ changes (or $\beta$) changes?
- idea behind result 2:
   - assume 2 players and interior equilibrium (i.e. $\partial u_i/\partial a_i=0$ in equilibrium)
   - assume strictly concave utility functions, i.e. $\partial^2 u_i/\partial a_i^2<0$
   - if $\tau$ increases, how does this affect marginal utility $\partial u_i/\partial a_i$?
   - can $a_1$ increase and $a_2$ decrease if $\tau$ increases?
# no: MU_2>0

** "Supermodularizing": Tricks I
*** Example: Cournot 						    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
Two firms with zero marginal costs set quantities $q_i$. The resulting market price is $1-q_1-q_2$. Firm $i$ maximizes its profit $q_i(1-q_i-q_j)$.

*** 							    :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- Is this game supermodular?
- Any idea what to do?
# let a_1=q_1 and a_2=-q_2; resulting game is supermodular

** "Supermodularizing": Tricks II
- We use again the price competition model but now we assume a logit demand
$$D_i(p_i,p_j)=\frac{1}{e^{p_i-p_j}+1}$$
- profits are then 
$$\pi_i(p_i,p_j)=\frac{p_i}{e^{p_i-p_j}+1}$$
which do not satisfy $\partial^2 \pi_i/\partial p_1\partial p_2\geq 0$
- trick:
   - the price maximizing $\pi_i(p_i,p_j)$ is the same that maximizes $log(\pi_i(p_i,p_j))$
   - let firms maximize log profits $u_i(p_i,p_j)=log (\pi_i(p_i,p_j))= log(p_i)-log(e^{p_i-p_j}+1)$ which satisfies $\partial^2 u_i/\partial p_1\partial p_2\geq 0$ (check!)

** Extensions
- What if each player takes several actions?\\ e.g. a firm sets price, quality and warranty length
- $A_i=[\underline y_i^1,\bar y_i^1]\times [\underline y_i^2,\bar y_i^2]\times \dots \times [\underline y_i^{k_i},\bar y_i^{k_i}]$
- hence, an action of player $i$ is now a vector $(a_i^1,a_i^2,\dots,a_i^{k_i})$
- supermodularity in this setup:
   - $\frac{\partial^2 u_i}{\partial a_i^m \partial a_j^n}\geq 0$ for all $i\neq j$ and $1\leq m\leq k_i$ and $1\leq n\leq k_j$
   - $\frac{\partial^2 u_i}{\partial a_i^m \partial a_i^n}\geq0$ for all $i$ and $1\leq m< n\leq k_i$
- with these assumptions all results still hold


* Revision questions and exercises

** Revision questions
- Why are we interested in supermodular games?
-  How are (simple smooth) supermodular games defined? (what is the crucial assumption?)
-  Explain the "increasing differences" property. 
-  What is the main result for supermodular games? What does it imply for the case that the game has only one pure strategy Nash equilibrium?
-  What do we mean by "comparative statics" and what kind of comparative static result is special for supermodular games?
-  What kind of tricks can you use to "make a game supermodular"?

reading: Amir (2005) p.636-649; 

*reading: Milgrom and Roberts (1990) (introduction+sections 2+4)

** Exercises I
-  Exercise 1:
   1. Take the standard Bertrand model with /homogenous/ goods: 2 firms have costs 0 and set a price $p_i$. There is one consumer who buys from the firm with the lower price (as long as this price is below his valuation $v$). Is this game supermodular?
   2. Choose a game theoretic model from another course you have taken and check whether the game was supermodular (or could be transformed into a supermodular model using one of the tricks).
-  Exercise 2:\\
   Complete the proof of supermodularity result 1 by showing that $(\bar u_1,\bar u_2,\dots)$ is a Nash equilibrium.
# -  Exercise 3*: 
# Check whether a Hotelling game pricing game (where the two firms are located at 0 and 1) is supermodular.

** Exercises II
-  *Exercise 3:\\ 
   Assume in addition to the assumptions so far that $u_i$ is strictly concave: $\partial^2 u_i/\partial a_i^2<0$. Show that each $A_i^k$ (in the iterative elimination of dominated actions) is an interval and conclude that $U_i$ is an interval.
# If in step $k$ action $a_i'$ is dominated by $a_i''>a_i'$, then $a_i''$ also dominates all actions $a_i'''<a_i'$ in step k: Follows for any given $a_{-i}$ from concavity.
# If in step $k$ action $a_i'$ is dominated by $a_i''<a_i'$, then $a_i''$ also dominates all actions $a_i'''>a_i'$ in step k.
# From the two statements above it follows that if $a_i^1<a_i^2<a_i^3$ and $a_i^2$ is eliminated in step k then it is impossible that both $a_i^1$ and $a_i^3$ are in $A_i^k$

