#+TITLE:    Perfect equilibrium in strategic form games
#+AUTHOR:    Christoph Schottmueller
#+EMAIL:    
#+DATE:     
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t 
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc 
#+INFOJS_OPT: view:nil toc:nil ltoc:nil mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_HEAD: <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"> </script>

We will use the third definition of perfect equilibrium that we used in the lecture.



#+BEGIN_definition
*Definition:* /\alpha is the limit of a sequence (\alpha(\varepsilon ))_{\varepsilon \rightarrow 0} of completely mixed strategies such that $\alpha$ is a best response to \alpha(\varepsilon) for \varepsilon  small enough./
#+END_definition

Let us start with a Nash equilibrium \alpha. Say we could for each player i find a completely mixed strategy \beta_i such that \alpha_i is a best response to (1-\varepsilon)\alpha_{-i}+\varepsilon\beta_{-i} for \varepsilon>0 small enough. In this case, \alpha has to be a perfect equilibrium: Since \alpha is a Nash equilibrium \alpha_i is a best response to \alpha_{-i}. But then \alpha_i will also be a best response to (1-\varepsilon')\alpha_{-i}+\varepsilon'\beta_{-i} for \varepsilon'<\varepsilon and the definition above gives the result.

All we have to do to verify that a given equilibrium is perfect is therefore to find a suitable \varepsilon and \beta. Below is a little program that tries exactly this. We use the simplest possible example.


#+CAPTION: Example
#+ATTR_HTML: :border 2 :rules all :frame border :align center
|   | L   | R   |
|---+-----+-----|
| U | 1,1 | 0,0 |
| D | 0,0 | 0,0 |

#+BEGIN_SRC python :exports both :results output
  from operator import add, mul, sub
  from openopt import SNLE, GLP

  #simple 2x2 example
  game = [[(1,1),(0,0)],[(0,0),(0,0)]]
  alpha = [(0.,1.),(0.,1.)]

  #adding a strictly dominated action to 2x2 example changes outcome
  #game = [[(1,1),(0,0),(-2,-1)],[(0,0),(0,0),(-2,0)],[(-1,-2),(0,-2),(-2,-2)]]
  #alpha = [(0.,1.,0.),(0.,1.,0.)]

  #3 player example: no perfect eq despite no weakly dominated strat
  #game = [[[(1,1,1),(1,1,1)],[(1,0,1),(0,0,1)]], [[(1,0,0),(0,1,0)],[(0,1,2),(1,0,0)]]]
  #alpha = [(0.,1.),(1.,0.),(1.,0.)]

  n = len(alpha) #number of players

  #if called with args (game,strat,1.0,n-1) help returns a list of lists
  #where each inner list corresponds to an action profile
  # and contains the expected utility contribution of this action profile
  # for each player given that the players use strategies "strat"
  def help(subgame,strat,prob,j):
      x = []
      if type(subgame)==tuple: #in this case prob is the prob of the action profile corresponding to the tuple subgame
          temp = [item*prob for item in subgame]#makes a list of EU contributions from this action profile
          return temp
      else:
          i = 0
          while i < len(subgame):#go through all actions of a player and weight every action according to player j's mixed strategy
              y = help(subgame[i], strat,prob*strat[j][i],j-1)
              if type(y[0])==list:
                  x = x + y
              else:
                  x.append(y)
              i = i+1
      return x


  #given a mixed strategy for every player, EU returns the expected utiliy of all players
  def EU(strat):
      temp = [0.]*n
      payoffs = help(game,strat,1.0,n-1)
      for item in payoffs:
          temp = map(add,temp,item)#elementwise addition
      return temp

  #given a mixed strategy profile, returns best response utilities of all players
  def brU(strat):
      out = []
      for i in range(n):
          xmini = strat[:i]
          xplusi = strat[i+1:]
          ui = -1000.#this initialization assumes that all payoffs are above -1000
          for act in range(len(alpha[i])):#calculates EU for each action of Pi to get br utility
              ui = max(ui,EU(xmini + [tuple(act*[0.]+[1.]+[0.]*(len(alpha[i])-1-act))] + xplusi)[i] )
          out.append(ui)
      return out


  #gives EU of every player if he plays alpha_i and others play as in strat
  def alphaU(strat):
      out = []
      for i in range(n):
          xmini = strat[:i]
          xplusi = strat[i+1:]
          ui = EU(xmini + [alpha[i]] + xplusi)[i] 
          out.append(ui)
      return out


  #m is total number of actions (of all players)
  m = 0
  mvec=[]
  aggm = []
  for item in alpha:
      length = len(item)
      aggm.append(m)
      m = m + length
      mvec.append(length)
  aggm.append(m)    
      

  lb = [0.005]*m #lower bound above zero as beta has to be totally mixed
  ub = [0.995]*m
  Aeq = []
  beq = []
  x0=[]
  for i in range(n):
      Aeq.append([0.]*aggm[i]+[1.]*mvec[i]+[0.]*(m-aggm[i+1]))
      beq.append(1.)
      x0 = x0 + mvec[i]*[1./mvec[i]]


  e = [0.01]*m #fix epsilon to be 0.01
  mine = [0.99]*m #1-epsilon

  #makes one long array out of the many tuples in alpha
  alphalist = []
  for item in alpha:
      for subitem in item:
          alphalist.append(subitem)

  #for a strategy profile beta given as flat list, this returns brU-alphaU 
  # if alpha is best response for each plyer this is list of 0s, otherwise >0
  def obj(beta):
      mix = map(add,map(mul,mine,alphalist),map(mul,e,beta))
      mixstrat=[]
      for player in range(n):#formats the long lists as strategy profiles
          mixi = tuple(mix[aggm[i]:aggm[i+1]])
          mixstrat.append(mixi)
      out = map(sub,brU(mixstrat),alphaU(mixstrat))
      return out

  #try to find a beta where obj=0
  p = SNLE(obj,x0, lb=lb,ub=ub,Aeq=Aeq,beq=beq,ftol=1e-8)
  r = p.solve('nssolve')


  if r.stopcase==1:
      #format solution as list of mixed strategies
      out = []
      for i in range(n):
          strat_i = [round(item,3) for item in r.xf[aggm[i]:aggm[i+1]]]
          out.append(tuple(strat_i))
      #print solution
      print 'alpha=',alpha,' is perfect equilibrium. beta equals',out
  else:
      print 'alpha=',alpha, ' might not be a perfect equilibrium'
#+END_SRC

There are two caveats to this numerical solution:
- /If no solution is obtained the equilibrium might still be perfect./ The program fixes \varepsilon to be 0.01 and restricts \beta such that the probability on each actions is at least 0.005. In theory, there could be a completely mixed \beta that works but puts probability of less than 0.005 on some action. Of course, we can try smaller lower bounds for \beta but you should keep in mind that there is a lower bound for numerical precision (which admittedly is much lower than 0.005) and that you have to adjust the tolerance ftol in the equation solver if you lower bound is substantially lower.
- /If a solution is obtained, it might still not be a prefect equilibrium./ Suppose \alpha was not a best response but there is another strategy that yields 1^{-40} more. The numerical equation solver would judge that 1^{-40} is zero and view \alpha as a best response. For this reason, the solver above is not suitable if the payoffs in your game differ by very small amounts. For example, write in the example game above (1^{-40},1^{-40}) as payoff for (U,L) (instead of (1,1)). The solver will then think that (D,R) is a perfect equilibrium although it is not.
