#+TITLE:    Finding mixed Nash equilibria in finite two player games
#+AUTHOR:    Christoph
#+EMAIL:    
#+DATE:      2015-07-31 Fri
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:nil mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport


# * Indifference condition: Brute force (DID NOT WORK YET)

# This is the way we normally use to calculate mixed Nash equilibria by hand: We guess a support, i.e. which actions are used by each player in equilibrium, and then we try to find a mixed strategy by /the other player/ that would make the first player indifferent between the actions in his support.

#+BEGIN_SRC python :exports none :results output :tangle NE_indiff
  from openopt import SNLE

  payoffs = [[(0,0),(3,1)],[(1,3),(1,1)]]#these are the payoffs from the game table; each row in the game table is a list of payoff tuples; the game table is then a list of these rows

  n = len(payoffs)#this is the number of actions of P1
  m = len(payoffs[0])#this is the number of actions of P2
  #next we extract the payoffs of only player 1 from the payoffs above
  payoff1 = []
  for i in payoffs:
      temp = []
      for j in i:
          temp.append(j[0])
      payoff1.append(temp)

  #now we extract the payoffs for P2
  payoff2 = []
  for i in payoffs:
      temp = []
      for j in i:
          temp.append(j[1])
      payoff2.append(temp)


  #now we have to construct the set of all possible supports
  supp1 = [(0,)]
  for i in range(1,n):
      temp = []
      for j in supp1:
          temp.append(j+(i,))
      temp.append((i,))
      supp1 = supp1 + temp

  supp2 = [(0,)]
  for i in range(1,m):
      temp = []
      for j in supp2:
          temp.append(j+(i,))
      temp.append((i,))
      supp2 = supp2 + temp

  #expecte utility of P1 when using action a1 while P2 uses the mixed strategy strat2
  def EU1(a1,strat2):
      return dot(payoff1[a1],strat2)#dot gives the vector "dot-product" of two arrays

  def EU2(a2,strat1):
      temp = 0
      i = 0
      while i<n:
          temp = temp + payoff2[i][a2]*strat1[i]
          i+=1
      return temp

  #the following function checks whether for a given support of P1 and P2 there is an equilibrium, i.e. a mixed strategy profile where players are indifferent between the actions in their support and where they prefer the actions in their support to the one's outside the support
  def check_eq(su1,su2):
      f1 = ()#this will contain the indifference conditions
      h1 = []#this will contain the optimality conditions
      ub1 = []#upper bound on probabilities (will contain 1s)
      lb1 = []#lower bound on proabilities (will contain 0s)
      Aeq = [[1.0]*m]#the condition that probabilities sum to beq
      beq = [1.0]
      x01 = []
      i = 0
      while i<n:
          if i in su1:
              f1 = f1 + (lambda x: EU1(su1[i],x)-EU1(su1[0],x),)
              #f1.append(lambda x: EU1(su1[i],x)-EU1(su1[0],x))
          else:
              h1.append(lambda x: EU1(su1[i],x)-EU1(su1[0],x))
          i = i+1
      i = 0
      while i<m:
          ub1.append(1.0)
          lb1.append(0.0)
          if i in su2:
              x01.append(1.0/len(su2))
          else:
              temp = [0.0]*m
              temp[i] = 1.0
              Aeq.append(temp)
              beq.append(0.0)
          i = i+1
      print lb1,ub1,h1,Aeq,beq
      p1 = SNLE(f1,x01, lb=lb1,ub=ub1,c=h1,Aeq=Aeq,beq=beq,contol=1e-4,gtol=1e-6,maxIter=1000)
      r1 = p1.solve('nssolve')
      f2 = ()#this will contain the indifference conditions
      h2 = []#this will contain the optimality conditions
      ub2 = []#upper bound on probabilities (will contain 1s)
      lb2 = []#lower bound on proabilities (will contain 0s)
      Aeq = [[1.0]*n]#the condition that probabilities sum to beq
      beq = [1.0]
      x02 = []
      i = 0
      while i<m:
          if i in su2:
              f2 = f2 + (lambda x: EU2(su2[i],x)-EU2(su2[0],x),)
              #f2.append(lambda x: EU2(su2[i],x)-EU2(su2[0],x))
          else:
              h2.append(lambda x: EU2(su2[i],x)-EU2(su2[0],x))
          i = i+1
      i = 0
      while i<n:
          ub2.append(1.0)
          lb2.append(0.0)
          if i in su1:
              x02.append(1.0/len(su1))
          else:
              temp = [0.0]*n
              temp[i] = 1.0
              Aeq.append(temp)
              beq.append(0.0)
          i = i+1
      p2 = SNLE(f2,x02, lb=lb2,ub=ub2,c=h2,Aeq=Aeq,beq=beq,contol=1e-4,gtol=1e-6,maxIter=1000)
      r2 = p2.solve('nssolve')
      if r1.stopcase == 1 and r2.stopcase==1:
          return r2.xf,r1.xf
      else:
          return None

  check_eq((0,1),(0,1))
  stop
  for i in supp1:
      for j in supp2:
          eq = []
          z = check_eq(i,j)
          if z != None:
              eq.append(z)
#+END_SRC



* Using a numerical approach based on solving an equation system

In a mixed equilibrium, each player uses only best responses with positive probability.  Denote the mixed strategy of player $i$ by the vector $x_i$ (which contains for each action the probability with which it is played). Denoting the expected utility for player $i$ when playing a best response as $EU_i^{br}$ (this will of course depend on $x_{-i}$ which we omit for brevity), we can write the vector 
$$\Delta_i(x_{-i})=(EU_i(a_1)-EU_i^{br},EU_i(a_2)-EU_i^{br}\dots EU_i(a_n)-EU_i^{br})$$ 
as the vector containing for each action of player $i$ the difference of the expected utility when taking this action and when taking the best response. Clearly, at least one entry in this vector is zero (each entry corresponding to a best response) and all other entries are negative. Therefore, we can describe an equilibrium by the following equations
$$\Delta_i(x_{-i})x_i=0\qquad \text{for all players } i$$
together with the feasibility constraints 
$$\mathbf{0}\leq x_i\leq \mathbf{1}\qquad \text{ and }\qquad x_i\mathbf{1}=1.$$
This is a simple system of equations with constraints and we can use a standard solver to get a solution, i.e. an equilibrium.

#+BEGIN_SRC python :exports both :results output
  from openopt import SNLE, GLP
  from numpy import *

  payoffs = [[(0,0),(3,1)],[(1,3),(1,1)]]#these are the payoffs from the game table; each row in the game table is a list of payoff tuples; the game table is then a list of these rows

  n = len(payoffs)#this is the number of actions of P1
  m = len(payoffs[0])#this is the number of actions of P2
  #next we extract the payoffs of only player 1 from the payoffs above
  payoff1 = []
  for i in payoffs:
      temp = []
      for j in i:
          temp.append(j[0])
      payoff1.append(temp)

  #now we extract the payoffs for P2
  payoff2 = []
  for i in payoffs:
      temp = []
      for j in i:
          temp.append(j[1])
      payoff2.append(temp)

  #expected utility of P1 when using action a1 while P2 uses the mixed strategy strat2
  def EU1(a1,strat2):
      return dot(payoff1[a1],strat2)#dot gives the vector "dot-product" of two arrays
  #expected utility of P2 when using action a2 while P1 uses the mixed strategy strat1
  def EU2(a2,strat1):
      temp = 0
      i = 0
      while i<n:
          temp = temp + payoff2[i][a2]*strat1[i]
          i += 1
      return temp

  #This function takes a vecor x which contains both a mixed strategy of P1 (in the first n elements) and also a mixed strategy of P2 (in the following m elements). The output of the function is the Delta described above but again it returns the Delta for both players
  def Delta(x):
      x1 = x[:n]#P1's mixed strategy
      x2 = x[n:]#P2's mixed strategy
      EU1max = 0.0#will containt the best response EU of P1
      EU1list = []#will become Delta_1(x2)
      i = 0
      while i<n:#loop through all actions of P1
          temp = EU1(i,x2)
          EU1max = max(temp,EU1max)
          EU1list.append(temp)
          i+=1
      EU1list = [z - EU1max for z in EU1list]#now EU1list is the Delta_1(x2) described above
      i = 0
      EU2list = []
      EU2max = 0.0
      while i<m:
          temp = EU2(i,x1)
          EU2max = max(temp,EU2max)
          EU2list.append(temp)
          i+=1
      EU2list = [y - EU2max for y in EU2list]
      EUlist = EU1list + EU2list
      return EUlist

  #multiplies the vectors x and Delta(x); this product has to be 0 in equilibrium
  def product(x):
      return dot(x,Delta(x))

  lb = [0.0]*(n+m)#lower bound to ensure that all probabilities are above 0
  ub = [1.0]*(n+m)#upper bound ensures that all probs are below 1
  Aeq = [[1.0]*n+[0.0]*m,[0.0]*n+[1.0]*m]#constraints that ensure that both the  mixed strategy of P1 and P2 sum to 1
  beq = [1.0,1.0]
  x0 = [1.0/n]*n+[1.0/m]*m#arbitrary starting value for the algorithm 

  p = SNLE(product,x0,lb=lb,ub=ub,Aeq=Aeq,beq=beq)
  r = p.solve('nssolve')

  if r.stopcase==1:
      print 'equilibrium: P1 plays',r.xf[:n],3,' and P2 plays',r.xf[n:]
  else:
      print 'Error: solver cannot find an equilibrium'


#+END_SRC

Note that the program above will give you only one equilibrium and not all equilibria. In principle, this could be changed by either trying many different starting values or by using a "global" equation solver that can find all solutions. 
